--CREATE VIEW
CREATE VIEW Top10Orders AS SELECT * FROM orders ORDER BY OrderTotal DESC LIMIT 10;

-- DROP VIEW
DROP VIEW Top10Orders;

--UPDATE VIEW
UPDATE Top10Orders SET OrderTotal = 10000 WHERE OrderID = 1;